packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true

onlyBuiltDependencies:
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
