/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const Role = {
  super_admin: "super_admin",
  outlet_admin: "outlet_admin",
  worker: "worker",
  driver: "driver",
  customer: "customer",
} as const;

export type Role = (typeof Role)[keyof typeof Role];

export const WorkerStation = {
  washing: "washing",
  ironing: "ironing",
  packing: "packing",
} as const;

export type WorkerStation = (typeof WorkerStation)[keyof typeof WorkerStation];

export const OrderStatus = {
  Menunggu_Penjemputan_Driver: "Menunggu_Penjemputan_Driver",
  Laundry_Sedang_Menuju_Outlet: "Laundry_Sedang_Menuju_Outlet",
  Laundry_Telah_Sampai_Outlet: "Laundry_Telah_Sampai_Outlet",
  Laundry_Sedang_Dicuci: "Laundry_Sedang_Dicuci",
  Laundry_Sedang_Disetrika: "Laundry_Sedang_Disetrika",
  Laundry_Sedang_Dipacking: "Laundry_Sedang_Dipacking",
  Menunggu_Pembayaran: "Menunggu_Pembayaran",
  Laundry_Sedang_Dikirim_Menuju_Customer:
    "Laundry_Sedang_Dikirim_Menuju_Customer",
  Laundry_Telah_Diterima_Customer: "Laundry_Telah_Diterima_Customer",
} as const;

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export const StationName = {
  washing: "washing",
  ironing: "ironing",
  packing: "packing",
} as const;

export type StationName = (typeof StationName)[keyof typeof StationName];

export const MismatchStatus = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
} as const;

export type MismatchStatus =
  (typeof MismatchStatus)[keyof typeof MismatchStatus];

export const PaymentGatewayStatus = {
  pending: "pending",
  paid: "paid",
  failed: "failed",
  expired: "expired",
  cancelled: "cancelled",
} as const;

export type PaymentGatewayStatus =
  (typeof PaymentGatewayStatus)[keyof typeof PaymentGatewayStatus];

export const DriverJobStatusEnum = {
  in_transit: "in_transit",
  on_delivery: "on_delivery",
  done: "done",
} as const;

export type DriverJobStatusEnum =
  (typeof DriverJobStatusEnum)[keyof typeof DriverJobStatusEnum];

export const WorkerShiftDay = {
  mon: "mon",
  tue: "tue",
  wed: "wed",
  thu: "thu",
  fri: "fri",
  sat: "sat",
  sun: "sun",
} as const;

export type WorkerShiftDay =
  (typeof WorkerShiftDay)[keyof typeof WorkerShiftDay];
